name: flake8  # 工作流的名称

on:
  push:  # 定义在 Push 事件时触发工作流
    branches:
      - main  # 监听 main 分支的推送事件

jobs:
  python-formatting:  # 第一个作业名称为 python-formatting
    runs-on: ubuntu-latest  # 在 Ubuntu 最新版本环境下运行作业
    steps:
      - name: Checkout  # 步骤1: 检出代码
        uses: actions/checkout@v4

      - name: Setup Python  # 步骤2: 设置 Python 环境
        uses: actions/setup-python@v4
        with:
          python-version: 3.9  # 指定 Python 版本为 3.9

      - name: Install flake8 and run checks  # 步骤3: 安装 flake8 并运行检查
        run: |
          pip install flake8
          echo "Running flake8 on changed files..."
          flake8 --config=.flake8 $(git diff --name-only HEAD^) > flake8.log || echo "flake8 found issues"
          if [ -s flake8.log ]; then
            echo "::error::flake8 found issues. Please fix them before pushing."
            exit 1
          fi